from enum import Enum


class ConfigKeys(Enum):
    TURBONOMIC_URL = "TURBONOMIC_URL"
    TURBONOMIC_USER = "TURBONOMIC_USER"
    TURBONOMIC_PASS = "TURBONOMIC_PASS"
    APP_DOWNLOAD_DIRECTORY = "APP_DOWNLOAD_DIRECTORY"
    APP_CSV_PATH = "APP_CSV_PATH"
